FROM debian:9.5-slim

ADD entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

# https://github.com/xgqfrms/hello-github-actions/new/master?filename=action-a/Dockerfile
