name: A workflow for github
on: push

jobs:
  build:
    name: github action demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "xgqfrms"
